-- Fleetify Database Schema (MySQL 8.0 InnoDB)

CREATE DATABASE IF NOT EXISTS fleetify CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE fleetify;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    role ENUM('SA', 'APPROVAL') NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS vehicles (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    license_plate VARCHAR(20) NOT NULL UNIQUE,
    model VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS master_items (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    item_name VARCHAR(150) NOT NULL,
    type ENUM('PART', 'SERVICE') NOT NULL,
    price DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS maintenance_reports (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    vehicle_id BIGINT UNSIGNED NOT NULL,
    created_by BIGINT UNSIGNED NOT NULL,
    odometer INT UNSIGNED NOT NULL,
    complaint TEXT NOT NULL,
    status ENUM('PENDING_APPROVAL', 'APPROVED', 'COMPLETED') NOT NULL DEFAULT 'PENDING_APPROVAL',
    initial_photo VARCHAR(500) DEFAULT NULL,
    proof_photo VARCHAR(500) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_reports_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(id) ON DELETE RESTRICT,
    CONSTRAINT fk_reports_user FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS report_items (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    report_id BIGINT UNSIGNED NOT NULL,
    item_id BIGINT UNSIGNED NOT NULL,
    quantity INT UNSIGNED NOT NULL DEFAULT 1,
    price_snapshot DECIMAL(12, 2) NOT NULL,
    CONSTRAINT fk_report_items_report FOREIGN KEY (report_id) REFERENCES maintenance_reports(id) ON DELETE CASCADE,
    CONSTRAINT fk_report_items_item FOREIGN KEY (item_id) REFERENCES master_items(id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE INDEX idx_reports_status ON maintenance_reports(status);
CREATE INDEX idx_reports_created_at ON maintenance_reports(created_at);
